# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='作品类别')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加的时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
        ),
    ]
