# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0002_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='文章的图片'),
        ),
    ]
