# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0003_auto_20180704_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='img',
            field=models.ImageField(default='/static/images/nocover.jpg', upload_to='images', verbose_name='文章的图片'),
        ),
    ]
